Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -146,81 +146,81 @@ jobs:
         run: |
           sleep 10
 
-  virustotal-scan:
-    needs: [ upload-to-github ]
-    uses: nikhilbadyal/ghactions/.github/workflows/virustotal-scan.yml@main
-    with:
-      FILES: |
-        .apk$
-      request_rate: 4
-    if: inputs.VIRUSTOTAL_SCAN
-    secrets:
-      VT_API_KEY: ${{ secrets.VT_API_KEY }}
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # virustotal-scan:
+  #   needs: [ upload-to-github ]
+  #   uses: nikhilbadyal/ghactions/.github/workflows/virustotal-scan.yml@main
+  #   with:
+  #     FILES: |
+  #       .apk$
+  #     request_rate: 4
+  #   if: inputs.VIRUSTOTAL_SCAN
+  #   secrets:
+  #     VT_API_KEY: ${{ secrets.VT_API_KEY }}
+  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  upload-to-telegram:
-    needs: [ upload-to-github ]
-    uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
-    if: inputs.TELEGRAM_NO_ROOT_UPLOAD
-    secrets:
-      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
-      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
-      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-      TELEGRAM_STICKER_ID: ${{ secrets.TELEGRAM_STICKER_ID }}
-      MESSAGE: ${{ secrets.MESSAGE_NON_ROOT }}
+  # upload-to-telegram:
+  #   needs: [ upload-to-github ]
+  #   uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
+  #   if: inputs.TELEGRAM_NO_ROOT_UPLOAD
+  #   secrets:
+  #     TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
+  #     TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
+  #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+  #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+  #     TELEGRAM_STICKER_ID: ${{ secrets.TELEGRAM_STICKER_ID }}
+  #     MESSAGE: ${{ secrets.MESSAGE_NON_ROOT }}
 
-  upload-to-telegram-root:
-    needs: [ upload-to-telegram ]
-    uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
-    if: inputs.TELEGRAM_ROOT_UPLOAD
-    secrets:
-      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
-      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
-      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-      DOWNLOAD_GITHUB_REPOSITORY: ${{ secrets.ROOT_DOWNLOAD_GITHUB_REPOSITORY }}
-      MESSAGE: ${{ secrets.MESSAGE_ROOT }}
+  # upload-to-telegram-root:
+  #   needs: [ upload-to-telegram ]
+  #   uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
+  #   if: inputs.TELEGRAM_ROOT_UPLOAD
+  #   secrets:
+  #     TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
+  #     TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
+  #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+  #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+  #     DOWNLOAD_GITHUB_REPOSITORY: ${{ secrets.ROOT_DOWNLOAD_GITHUB_REPOSITORY }}
+  #     MESSAGE: ${{ secrets.MESSAGE_ROOT }}
 
-  apprise-notifier:
-    needs: build-apk
-    name: Apprise Notifier
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    if: inputs.APPRISE_NOTIFY
+  # apprise-notifier:
+  #   needs: build-apk
+  #   name: Apprise Notifier
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   if: inputs.APPRISE_NOTIFY
 
-    steps:
-      - name: Download Already Built APKs
-        uses: actions/download-artifact@main
-        with:
-          name: Built-APKs
+  #   steps:
+  #     - name: Download Already Built APKs
+  #       uses: actions/download-artifact@main
+  #       with:
+  #         name: Built-APKs
 
-      - name: Find all built apks
-        id: ff
-        run: |
-          apk_list=""
-          for filename in $(find . -name "*-output.apk" -type f); do
-            apk_list="$apk_list,$filename"
-          done
-          apk_list=${apk_list:1}
-          echo "apks=$apk_list" >> "$GITHUB_OUTPUT"
-          is_present=$([ -n "${{ secrets.APPRISE_URL }}" ] && echo true || echo false );
-          echo "has_apprise_url=$is_present"  >> $GITHUB_OUTPUT
-      - name: Print files
-        run: echo "${{ steps.ff.outputs.apks }} ${{ steps.ff.outputs.has_apprise_url }}"
+  #     - name: Find all built apks
+  #       id: ff
+  #       run: |
+  #         apk_list=""
+  #         for filename in $(find . -name "*-output.apk" -type f); do
+  #           apk_list="$apk_list,$filename"
+  #         done
+  #         apk_list=${apk_list:1}
+  #         echo "apks=$apk_list" >> "$GITHUB_OUTPUT"
+  #         is_present=$([ -n "${{ secrets.APPRISE_URL }}" ] && echo true || echo false );
+  #         echo "has_apprise_url=$is_present"  >> $GITHUB_OUTPUT
+  #     - name: Print files
+  #       run: echo "${{ steps.ff.outputs.apks }} ${{ steps.ff.outputs.has_apprise_url }}"
 
-      - name: Upload to Telegram
-        uses: nikhilbadyal/ghaction-apprise@main
-        with:
-          APPRISE_URL: ${{ secrets.APPRISE_URL }}
-          APPRISE_NOTIFICATION_BODY: ${{ secrets.APPRISE_NOTIFICATION_BODY }}
-          APPRISE_NOTIFICATION_TITLE: ${{ secrets.APPRISE_NOTIFICATION_TITLE }}
-          APPRISE_ATTACHMENTS: ${{ steps.ff.outputs.apks }}
+  #     - name: Upload to Telegram
+  #       uses: nikhilbadyal/ghaction-apprise@main
+  #       with:
+  #         APPRISE_URL: ${{ secrets.APPRISE_URL }}
+  #         APPRISE_NOTIFICATION_BODY: ${{ secrets.APPRISE_NOTIFICATION_BODY }}
+  #         APPRISE_NOTIFICATION_TITLE: ${{ secrets.APPRISE_NOTIFICATION_TITLE }}
+  #         APPRISE_ATTACHMENTS: ${{ steps.ff.outputs.apks }}
 
-  cleanup:
-    name: GitHub Cleanup
-    if: inputs.CLEANUP
-    needs: [ upload-to-telegram ]
-    uses: ./.github/workflows/github-cleanup.yml
-    secrets:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # cleanup:
+  #   name: GitHub Cleanup
+  #   if: inputs.CLEANUP
+  #   needs: [ upload-to-telegram ]
+  #   uses: ./.github/workflows/github-cleanup.yml
+  #   secrets:
+  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
